server:
  port: 8082
spring:
  application:
    name: StudyDemo
  datasource:
    url: jdbc:mysql:///mybatis
    username: root
    password: root
#  data:
#    elasticsearch:
#      cluster-name: elasticsearch
#      cluster-nodes: 192.168.128.133:9300
  thymeleaf:
      mode: LEGACYHTML5
      encoding: UTF-8
      cache: false
      check-template-location: true
      enabled: true
      prefix: classpath:/templates/
  resources:
    static-locations: classpath:/static/
    chain:
      cache: false
mybatis:
  type-aliases-package: com.mumu.pojo
  mapper-locations: mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用
