server:
  port: 8081
spring:
  application:
    name: TestDay
  datasource:
    url: jdbc:mysql://192.168.128.1:3306/hngh_test
    username: root
    password: root
  thymeleaf:
    mode: LEGACYHTML5
    encoding: UTF-8
    cache: false
    check-template-location: true
    enabled: true
    prefix: classpath:/templates/

mybatis:
  type-aliases-package: com.jianlang.pojo
  mapper-locations: mapper/*.xml  #xml文件位置
  configuration:  #配置驼峰问题
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用




